# Identification manifest generation example (closed-set)
# Face modality, Multi-PIE dataset, no constraints, 50 identities, 3 gallery sample and 1 probe sample per identity.
# angle filter: angle equal or less then 30 degrees
public_dataset_root: "C:/Users/sebas/Documents/VUT_FIT_MIT/DP/PublicDataset"
random_seed: 42

identification_generation:
  number_of_identities: 50  # -1 means: use all identities
  gallery_samples_per_identity: 3
  probes_per_identity: 1 # -1 means: use all remaining samples per identity
  filters:
    angle: ["130", "140", "051", "050", "041"] # filter by camera e.g., "050" or "051"

output:
  csv_path: "bioverify/data/identification/identification_face_multipie_50_1_3_a_le30.csv"
  relative_paths: true

datasets:
  - dataset_path: "Face"
    dataset_name: "Multi-PIE"
    modality: "face"
    image_type: "HR_128"  #HR_128 or "LR_4x" or "both"