# Configuration for indexing the FV-USM finger vein dataset, 500 pairs

public_dataset_root: "C:/Users/sebas/Documents/VUT_FIT_MIT/DP/PublicDataset"

random_seed: 42

pair_generation:
  #genuine_per_identity: 2          # Or use max_genuine_pairs
  max_genuine_pairs: 250          # Hard limit, set to -1 for maximum possible pairs up to cap
  impostor_ratio: 1.0
  #max_impostor_pairs: 100         # no longer used

output:
  csv_path: "bioverify/data/pairs/pairs_finger_fvusm_500.csv"
  relative_paths: true

# Just one small dataset for testing
datasets:
  - dataset_path: "FingerVein/003-FV-USM"
    dataset_name: "FV-USM"
    modality: "finger"
    image_type: "roi"
    match_constraints:
      side: True
      finger: True
