# 1k pairs hands 11k hands dataset

public_dataset_root: "C:/Users/sebas/Documents/VUT_FIT_MIT/DP/PublicDataset"

random_seed: 42

pair_generation:
  #genuine_per_identity: 2          # Or use max_genuine_pairs
  max_genuine_pairs: 500          # Hard limit, set to -1 for maximum possible pairs up to cap
  impostor_ratio: 1.0
  #max_impostor_pairs: 100         # no longer used

output:
  csv_path: "bioverify/data/pairs/test_1k_11khands.csv"
  relative_paths: true

# Just one small dataset for testing
datasets:
  - dataset_path: "HandGeometry"
    dataset_name: "11k_Hands"
    modality: "hand"
    match_constraints:
      
